### ISSUE TITLE
Can't import synergia

### ISSUE THREAD

**Issue by prebys** [radiasoft/jupyter.radiasoft.org#5]
Suddenly, when I try to import synergia, I get an error from the one_turn_map.py module that it can't find "basic_toolkit":

>\>\>\> import synergia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py2/lib/synergia/synergia/__init__.py", line 11, in <module>
    import optics
  File "/home/vagrant/.pyenv/versions/py2/lib/synergia/synergia/optics/__init__.py", line 1, in <module>
    from matching import *
  File "/home/vagrant/.pyenv/versions/py2/lib/synergia/synergia/optics/matching.py", line 6, in <module>
    from one_turn_map import linear_one_turn_map
  File "/home/vagrant/.pyenv/versions/py2/lib/synergia/synergia/optics/one_turn_map.py", line 7, in <module>
    import basic_toolkit
ImportError: No module named basic_toolkit

Any ideas?

**Comment by robnagler** [comment]
I will take a look today.

**Comment by robnagler** [comment]
The build is happening. I'll close this (again) when it's installed on the server and known to be working. Will be a few hours.

**Comment by robnagler** [comment]
importing synergia works. Just stop your server via the Control Panel and start.
