### ISSUE TITLE
Simple program crashing when reading HDF5 file.

### ISSUE THREAD

**Issue by prebys** [radiasoft/jupyter.radiasoft.org#8]
This program (plot_losses.py) consistently crashes at the point it reads in loss_diagnostics.h5 on Jupyter.  If I import it as a notebook, a splash pops up that the kernel has crashed at the ...read() line. 

I have confirmed that it works fine on several other machines.

[plot_losses.zip](https://github.com/radiasoft/jupyter.radiasoft.org/files/959602/plot_losses.zip)

**Comment by robnagler** [comment]
I'm seeing the error on Jupyter, but not on my local environment. I'm investigating.

**Comment by robnagler** [comment]
Same docker image running on my Mac runs fine, but isn't working on apa20. The error doesn't occur in radiasoft/beamsim-jupyter:20170331.171528, but does occur in 20170419.181400. Trying to isolate.

FTR, the (uninformative) stack trace of the error is:

```text
#0  0x00007fffc9950948 in __pyx_pw_6tables_13hdf5extension_5Array_9_read_array (__pyx_v_self=0x7ffff157b5a0, __pyx_args=0x7ffff7f8e208, __pyx_kwds=0x0)
    at tables/hdf5extension.c:17738
#1  0x00007ffff7adccde in call_function (oparg=<optimized out>, pp_stack=0x7fffffffe070) at Python/ceval.c:4035
#2  PyEval_EvalFrameEx (f=f@entry=0x173e7b0, throwflag=throwflag@entry=0) at Python/ceval.c:2681
#3  0x00007ffff7add620 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=5,
    kws=0x7fffe74fa228, kwcount=0, defs=0x7fffe9cb56e8, defcount=1, closure=0x0) at Python/ceval.c:3267
#4  0x00007ffff7adc116 in fast_function (nk=0, na=5, n=<optimized out>, pp_stack=0x7fffffffe270, func=0x7fffe752dc08) at Python/ceval.c:4131
#5  call_function (oparg=<optimized out>, pp_stack=0x7fffffffe270) at Python/ceval.c:4056
#6  PyEval_EvalFrameEx (f=f@entry=0x7fffe74fa050, throwflag=throwflag@entry=0) at Python/ceval.c:2681
#7  0x00007ffff7add620 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1,
    kws=0x7ffff7e801d0, kwcount=0, defs=0x7fffe7539278, defcount=4, closure=0x0) at Python/ceval.c:3267
#8  0x00007ffff7adc116 in fast_function (nk=0, na=1, n=<optimized out>, pp_stack=0x7fffffffe470, func=0x7fffe752dc80) at Python/ceval.c:4131
#9  call_function (oparg=<optimized out>, pp_stack=0x7fffffffe470) at Python/ceval.c:4056
#10 PyEval_EvalFrameEx (f=f@entry=0x7ffff7e80050, throwflag=throwflag@entry=0) at Python/ceval.c:2681
#11 0x00007ffff7add620 in PyEval_EvalCodeEx (co=co@entry=0x7ffff7f932b0, globals=globals@entry=0x7ffff7f7a168, locals=locals@entry=0x7ffff7f7a168, args=args@entry=0x0,
    argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3267
#12 0x00007ffff7add749 in PyEval_EvalCode (co=co@entry=0x7ffff7f932b0, globals=globals@entry=0x7ffff7f7a168, locals=locals@entry=0x7ffff7f7a168) at Python/ceval.c:669
#13 0x00007ffff7b0151a in run_mod (arena=0x62edb0, flags=0x7fffffffe690, locals=0x7ffff7f7a168, globals=0x7ffff7f7a168, filename=0x621750 "\n", mod=<optimized out>)
    at Python/pythonrun.c:1371
#14 PyRun_FileExFlags (fp=fp@entry=0x621750, filename=filename@entry=0x7fffffffeb3b "plot_losses.py", start=start@entry=257, globals=globals@entry=0x7ffff7f7a168,
    locals=locals@entry=0x7ffff7f7a168, closeit=closeit@entry=1, flags=0x7fffffffe690) at Python/pythonrun.c:1357
#15 0x00007ffff7b02aa7 in PyRun_SimpleFileExFlags (fp=fp@entry=0x621750, filename=0x7fffffffeb3b "plot_losses.py", closeit=1, flags=flags@entry=0x7fffffffe690)
    at Python/pythonrun.c:949
#16 0x00007ffff7b02fc3 in PyRun_AnyFileExFlags (fp=fp@entry=0x621750, filename=<optimized out>, closeit=<optimized out>, flags=flags@entry=0x7fffffffe690)
    at Python/pythonrun.c:753
#17 0x00007ffff7b18955 in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:640
#18 0x00007ffff6d0afe0 in __libc_start_main () from /lib64/libc.so.6
#19 0x000000000040074e in _start ()
```

**Comment by robnagler** [comment]
Seems to be switch to tables 3.4 from 3.3. Does not happen in radiasoft/beamsim-jupyter:20170414.214737. To fix, I'll lock the version and rebuild.  For now, you should be able to do this in a terminal window in your container:

```
pip install -U tables==3.3.0
```

The new builds should be available in a few hours.

**Comment by robnagler** [comment]
The new Docker image is installed. To get changes, stop and restart your server.

**Comment by prebys** [comment]
I restarted the kernel, but I still needed to do
> pop install -U tables==3.3.0

Then it works.  

Thanks,
Eric

**Comment by robnagler** [comment]
Hi Eric, Could you run these commands and send me the output?

```sh
pyenv which python
pip show tables
```

Thanks!
